/**
 * Emergence Types — Sprint 4 (Skill Emergence)
 *
 * Extends pattern-detector types with session-aware sequence detection.
 * Feed 2.0 session fields (sessionId, turnNumber, priorIntentHash) from
 * SESSION-TELEMETRY P1 (06e2996) drive sequence pattern discovery.
 */

import type { Pillar } from '../conversation/types';
import type { LoggedAction, DetectedPattern, SkillProposal } from '../skills/pattern-detector';

// =============================================================================
// SESSION-AWARE TYPES
// =============================================================================

/**
 * A Feed 2.0 action enriched with session telemetry fields.
 * Extends LoggedAction with session context for grouping + sequencing.
 */
export interface SessionAction extends LoggedAction {
  sessionId: string;
  turnNumber: number;
  priorIntentHash?: string;
}

/**
 * A group of actions from the same session, ordered by turn number.
 */
export interface SessionGroup {
  sessionId: string;
  actions: SessionAction[];
  startTime: string;
  endTime: string;
  turnCount: number;
  uniqueIntents: number;
}

/**
 * A transition between two intents within a session.
 * e.g., "query" → "capture" or "classify" → "dispatch"
 */
export interface IntentTransition {
  fromIntent: string;
  toIntent: string;
  fromAction: string;
  toAction: string;
}

/**
 * A sequence of intent transitions detected across sessions.
 */
export interface IntentSequence {
  transitions: IntentTransition[];
  length: number;
  hash: string;
}

/**
 * A detected sequence pattern — repeated workflow transitions.
 */
export interface SequencePattern {
  sequence: IntentSequence;
  occurrences: SessionGroup[];
  frequency: number;
  avgTurns: number;
  commonPillar?: Pillar;
  commonTools: string[];
  firstSeen: string;
  lastSeen: string;
  completionRate: number;
}

// =============================================================================
// EMERGENCE SIGNAL
// =============================================================================

export type EmergenceSource = 'frequency' | 'sequence';

/**
 * A signal that a pattern has crossed the emergence threshold.
 * Generated by EmergenceMonitor from either frequency or sequence detection.
 */
export interface EmergenceSignal {
  id: string;
  source: EmergenceSource;
  frequencyPattern?: DetectedPattern;
  sequencePattern?: SequencePattern;
  frequency: number;
  lastOccurrence: string;
  avgTurns: number;
  completionRate: number;
  suggestedSkillName: string;
  description: string;
}

// =============================================================================
// DISMISSED PATTERNS
// =============================================================================

export interface DismissedPattern {
  signalId: string;
  patternHash: string;
  dismissedAt: string;
  cooldownUntil: string;
  reason?: string;
}

// =============================================================================
// PROPOSAL
// =============================================================================

/**
 * An emergence proposal delivered to Jim for approval.
 * Wraps an EmergenceSignal with delivery metadata.
 */
export interface EmergenceProposal {
  id: string;
  signal: EmergenceSignal;
  proposalText: string;
  suggestedSkillName: string;
  status: 'pending' | 'approved' | 'dismissed';
  createdAt: string;
  processedAt?: string;
  dismissReason?: string;
}

// =============================================================================
// CONFIG
// =============================================================================

export interface EmergenceConfig {
  /** Minimum occurrences to trigger emergence (default: 5) */
  minFrequency: number;
  /** Detection window in days (default: 14) */
  windowDays: number;
  /** Minimum completion rate for sequence patterns (default: 0.8) */
  minCompletionRate: number;
  /** Minimum distinct intent types in a sequence (default: 2) */
  minSequenceLength: number;
  /** Max proposals per day (default: 3) */
  maxProposalsPerDay: number;
  /** Cooldown after dismiss in days (default: 7) */
  dismissCooldownDays: number;
}

export const DEFAULT_EMERGENCE_CONFIG: EmergenceConfig = {
  minFrequency: 5,
  windowDays: 14,
  minCompletionRate: 0.8,
  minSequenceLength: 2,
  maxProposalsPerDay: 3,
  dismissCooldownDays: 7,
};

// =============================================================================
// MONITOR RESULT
// =============================================================================

export interface EmergenceCheckResult {
  signals: EmergenceSignal[];
  proposals: EmergenceProposal[];
  stats: {
    sessionsAnalyzed: number;
    sequencePatternsFound: number;
    frequencyPatternsFound: number;
    proposalsGenerated: number;
    skippedDismissed: number;
    skippedRateLimit: number;
  };
}

// =============================================================================
// TELEMETRY EVENTS
// =============================================================================

export type EmergenceEventType =
  | 'emergence_check'
  | 'proposal_generated'
  | 'proposal_approved'
  | 'proposal_dismissed'
  | 'skill_created';

export interface EmergenceEvent {
  type: EmergenceEventType;
  signalId?: string;
  proposalId?: string;
  skillName?: string;
  metadata?: Record<string, unknown>;
  timestamp: string;
}
